version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: bigfut/corpquiz-backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./corpquiz/nginx:/etc/nginx/conf.d
      - ./frontend/build:/usr/share/nginx/html/
      - ./corpquiz/docs/:/usr/share/nginx/html/api/v1/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend

  frontend:
    image: bigfut/corpquiz-frontend:latest
    volumes:
      - ./frontend/:/app/result_build/
    depends_on:
      - backend

volumes:
  static_value:
  media_value:
  db_value: